"""Versioned successor face of the retired ``order_block_registry`` (F12 v1 -> v2).

``tools/verify_formula_entrypoints.py`` enforces that a module retired with a MODULE-docstring
``RETIRED_DEFECTIVE`` banner has a versioned successor named ``<stem>_v*.py`` — retirement can
never silently remove a formula's production surface. The R-F12 implementation lives in
:mod:`triad_origin.structures.order_block_v2` (``ob.displacement_bos.v2``); this module is that
implementation's stem-preserving successor face and re-exports the complete public surface
verbatim. ONE implementation, one law — nothing is redefined here.
"""

from __future__ import annotations

from .order_block_v2 import (
    ACTIVE_ZONE_PHASES,
    BAR_OUT_OF_ORDER,
    BINDING_VALUE_NOT_DECLARED,
    BINDING_VALUE_NOT_INTEGER,
    BINDING_VALUE_NOT_RATIONAL,
    BOS_HORIZON_ELAPSED,
    BREAK_OUT_OF_ORDER,
    BROKEN,
    BlockedOnRatify,
    CONFIRMED_BY_BOS,
    DECLARED_OPPOSING_PREDICATE,
    DEFINING_REVISION,
    DISPLACED,
    EXPIRED,
    EnvelopeContractError,
    FIRST_TOUCH_KIND,
    FORMULA_ID,
    FRESH,
    GAP_BAR,
    INPUT_IDENTITY_CONFLICT,
    INVALIDATED,
    MITIGATED,
    NO_OPPOSING_ORIGIN,
    OB_ORIGIN_TIE,
    OB_TTL,
    ONE_BOS_ONE_LINEAGE,
    OPPOSING_BOS_BREAK,
    ORIGIN_CANDIDATE,
    PARAM_BOS_HORIZON,
    PARAM_BREAK_BUFFER,
    PARAM_LOOKBACK,
    PARAM_MITIGATION,
    PARAM_OPPOSING,
    PARAM_TTL,
    PARTIAL,
    PHASES,
    QUARANTINE_OVERFLOW_REASON,
    REQUIRED_PARAMETER_IDS,
    RETIRED_PREDECESSOR,
    SAME_EVENT_PRECEDENCE,
    SEQUENCE_GAP,
    STATE_KIND,
    STATE_VERSION_MISMATCH,
    TERMINAL_PHASES,
    TOUCHED,
    TRIGGER_OUT_OF_ORDER,
    VERSION,
    dominant_f12,
    evaluate,
    initial_state,
    note_gap,
    register_break,
    register_displacement,
    revise_bar,
)

__all__ = (
    "ACTIVE_ZONE_PHASES",
    "BAR_OUT_OF_ORDER",
    "BINDING_VALUE_NOT_DECLARED",
    "BINDING_VALUE_NOT_INTEGER",
    "BINDING_VALUE_NOT_RATIONAL",
    "BOS_HORIZON_ELAPSED",
    "BREAK_OUT_OF_ORDER",
    "BROKEN",
    "BlockedOnRatify",
    "CONFIRMED_BY_BOS",
    "DECLARED_OPPOSING_PREDICATE",
    "DEFINING_REVISION",
    "DISPLACED",
    "EXPIRED",
    "EnvelopeContractError",
    "FIRST_TOUCH_KIND",
    "FORMULA_ID",
    "FRESH",
    "GAP_BAR",
    "INPUT_IDENTITY_CONFLICT",
    "INVALIDATED",
    "MITIGATED",
    "NO_OPPOSING_ORIGIN",
    "OB_ORIGIN_TIE",
    "OB_TTL",
    "ONE_BOS_ONE_LINEAGE",
    "OPPOSING_BOS_BREAK",
    "ORIGIN_CANDIDATE",
    "PARAM_BOS_HORIZON",
    "PARAM_BREAK_BUFFER",
    "PARAM_LOOKBACK",
    "PARAM_MITIGATION",
    "PARAM_OPPOSING",
    "PARAM_TTL",
    "PARTIAL",
    "PHASES",
    "QUARANTINE_OVERFLOW_REASON",
    "REQUIRED_PARAMETER_IDS",
    "RETIRED_PREDECESSOR",
    "SAME_EVENT_PRECEDENCE",
    "SEQUENCE_GAP",
    "STATE_KIND",
    "STATE_VERSION_MISMATCH",
    "TERMINAL_PHASES",
    "TOUCHED",
    "TRIGGER_OUT_OF_ORDER",
    "VERSION",
    "dominant_f12",
    "evaluate",
    "initial_state",
    "note_gap",
    "register_break",
    "register_displacement",
    "revise_bar",
)
